import { createFileRoute } from "@tanstack/react-router";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Switch } from "@/components/ui/switch";
import { Bell, Check } from "lucide-react";
import { ReadinessBar } from "@/components/ReadinessBar";
import { useImporter, markAllRead, setNotifySetting } from "@/lib/importer-store";

export const Route = createFileRoute("/importer/notifications")({
  head: () => ({
    meta: [
      { title: "Notifications — Canta Importer" },
      { name: "description", content: "Payment, funding, compliance, shipment and receipt updates in one place." },
      { property: "og:title", content: "Notifications — Canta Importer" },
      { property: "og:description", content: "Payment, funding, compliance, shipment and receipt updates in one place." },
    ],
  }),
  component: NotificationsPage,
});

function NotificationsPage() {
  const s = useImporter();
  const unread = s.notifications.filter((n) => !n.read).length;

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <ReadinessBar status="Demo Preview" cue="Alerts in this demo are illustrative and generated by your own actions." />
      <header className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight flex items-center gap-2"><Bell className="h-5 w-5 text-primary" /> Notifications</h1>
          <p className="text-sm text-muted-foreground mt-1">{unread} unread update{unread === 1 ? "" : "s"}</p>
        </div>
        <Button size="sm" variant="outline" onClick={markAllRead}><Check className="h-4 w-4" /> Mark all as read</Button>
      </header>

      <Card className="p-4 shadow-card">
        <h2 className="font-semibold text-sm">How you get updates</h2>
        <div className="mt-3 space-y-3">
          {([["whatsapp", "WhatsApp notifications"], ["email", "Email notifications"], ["inApp", "In-app notifications"]] as const).map(([k, label]) => (
            <label key={k} className="flex items-center justify-between gap-3 text-sm">
              <span>{label}</span>
              <Switch checked={s.notifySettings[k]} onCheckedChange={(v) => setNotifySetting(k, v)} />
            </label>
          ))}
        </div>
      </Card>

      <div className="space-y-2">
        {s.notifications.map((n) => (
          <Card key={n.id} className={`p-3 shadow-card flex flex-wrap items-center justify-between gap-2 ${n.read ? "opacity-70" : ""}`}>
            <div className="min-w-0">
              <div className="text-sm">{n.text}</div>
              <div className="text-xs text-muted-foreground">{n.at}</div>
            </div>
            <Badge variant="outline" className="text-[10px]">{n.kind}</Badge>
          </Card>
        ))}
        {s.notifications.length === 0 && <div className="text-center text-sm text-muted-foreground py-10">No notifications yet.</div>}
      </div>
    </div>
  );
}
