/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiDocumentExtractionRouteImport } from './routes/ai-document-extraction'
import { Route as AiGrowthRouteImport } from './routes/ai-growth'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as BeneficiariesRouteImport } from './routes/beneficiaries'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataModelRouteImport } from './routes/data-model'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EscrowRouteImport } from './routes/escrow'
import { Route as FxRouteImport } from './routes/fx'
import { Route as ImporterRouteImport } from './routes/importer'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as KybOnboardingRouteImport } from './routes/kyb-onboarding'
import { Route as LandedCostRouteImport } from './routes/landed-cost'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MySuppliersRouteImport } from './routes/my-suppliers'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PayersRouteImport } from './routes/payers'
import { Route as PaymentLinksRouteImport } from './routes/payment-links'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SupplierPortalRouteImport } from './routes/supplier-portal'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TradeDeskRouteImport } from './routes/trade-desk'
import { Route as TradeNetworkRouteImport } from './routes/trade-network'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as UserStoriesRouteImport } from './routes/user-stories'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as VerificationCenterRouteImport } from './routes/verification-center'
import { Route as VerifiedBuyersRouteImport } from './routes/verified-buyers'
import { Route as VerifiedSuppliersRouteImport } from './routes/verified-suppliers'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as CollectionsNewRouteImport } from './routes/collections.new'
import { Route as ImporterCardsRouteImport } from './routes/importer.cards'
import { Route as MerchantKybRouteImport } from './routes/merchant.kyb'
import { Route as MerchantProfileRouteImport } from './routes/merchant.profile'
import { Route as PLinkIdRouteImport } from './routes/p.$linkId'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerActivityLogRouteImport } from './routes/partner.activity-log'
import { Route as PartnerCasesRouteImport } from './routes/partner.cases'
import { Route as PartnerClientsRouteImport } from './routes/partner.clients'
import { Route as PartnerCommissionsRouteImport } from './routes/partner.commissions'
import { Route as PartnerDisputesRouteImport } from './routes/partner.disputes'
import { Route as PartnerDocumentsRouteImport } from './routes/partner.documents'
import { Route as PartnerFxQuotesRouteImport } from './routes/partner.fx-quotes'
import { Route as PartnerLeadsRouteImport } from './routes/partner.leads'
import { Route as PartnerMarketersRouteImport } from './routes/partner.marketers'
import { Route as PartnerNewReferralRouteImport } from './routes/partner.new-referral'
import { Route as PartnerPaymentLinksRouteImport } from './routes/partner.payment-links'
import { Route as PartnerPayoutsRouteImport } from './routes/partner.payouts'
import { Route as PartnerReportsRouteImport } from './routes/partner.reports'
import { Route as PartnerSettingsRouteImport } from './routes/partner.settings'
import { Route as PartnerSolicitorsRouteImport } from './routes/partner.solicitors'
import { Route as PartnerTeamRouteImport } from './routes/partner.team'
import { Route as PayLinkIdRouteImport } from './routes/pay.$linkId'
import { Route as SupplierPortalIndexRouteImport } from './routes/supplier-portal.index'
import { Route as SupplierPortalBuyersRouteImport } from './routes/supplier-portal.buyers'
import { Route as SupplierPortalCreateInvoiceRouteImport } from './routes/supplier-portal.create-invoice'
import { Route as SupplierPortalDocumentsRouteImport } from './routes/supplier-portal.documents'
import { Route as SupplierPortalFxQuotesRouteImport } from './routes/supplier-portal.fx-quotes'
import { Route as SupplierPortalInvoicesRouteImport } from './routes/supplier-portal.invoices'
import { Route as SupplierPortalMessagesRouteImport } from './routes/supplier-portal.messages'
import { Route as SupplierPortalNgnBalanceRouteImport } from './routes/supplier-portal.ngn-balance'
import { Route as SupplierPortalNgnDetailsRouteImport } from './routes/supplier-portal.ngn-details'
import { Route as SupplierPortalPaymentRequestsRouteImport } from './routes/supplier-portal.payment-requests'
import { Route as SupplierPortalPayoutAccountsRouteImport } from './routes/supplier-portal.payout-accounts'
import { Route as SupplierPortalProfileRouteImport } from './routes/supplier-portal.profile'
import { Route as SupplierPortalReportsRouteImport } from './routes/supplier-portal.reports'
import { Route as SupplierPortalRequestsRouteImport } from './routes/supplier-portal.requests'
import { Route as SupplierPortalRmbBankAccountRouteImport } from './routes/supplier-portal.rmb-bank-account'
import { Route as SupplierPortalRmbWalletRouteImport } from './routes/supplier-portal.rmb-wallet'
import { Route as SupplierPortalSettingsRouteImport } from './routes/supplier-portal.settings'
import { Route as SupplierPortalSettlementRouteImport } from './routes/supplier-portal.settlement'
import { Route as SupplierPortalSettlementsRouteImport } from './routes/supplier-portal.settlements'
import { Route as SupplierPortalSupportRouteImport } from './routes/supplier-portal.support'
import { Route as SupplierPortalTeamRouteImport } from './routes/supplier-portal.team'
import { Route as SupplierPortalTradeFilesRouteImport } from './routes/supplier-portal.trade-files'
import { Route as SupplierPortalVerificationRouteImport } from './routes/supplier-portal.verification'
import { Route as SupplierPortalWalletRouteImport } from './routes/supplier-portal.wallet'
import { Route as SuppliersKybRouteImport } from './routes/suppliers.kyb'
import { Route as SuppliersProfileRouteImport } from './routes/suppliers.profile'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as TrackWhatsappRouteImport } from './routes/track.whatsapp'
import { Route as TradeDeskIndexRouteImport } from './routes/trade-desk.index'
import { Route as TradeDeskFileIdRouteImport } from './routes/trade-desk.$fileId'
import { Route as TreasuryCardsRouteImport } from './routes/treasury.cards'
import { Route as PartnerCasesIndexRouteImport } from './routes/partner.cases.index'
import { Route as PartnerCasesCaseIdRouteImport } from './routes/partner.cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDocumentExtractionRoute = AiDocumentExtractionRouteImport.update({
  id: '/ai-document-extraction',
  path: '/ai-document-extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGrowthRoute = AiGrowthRouteImport.update({
  id: '/ai-growth',
  path: '/ai-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesRoute = BeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataModelRoute = DataModelRouteImport.update({
  id: '/data-model',
  path: '/data-model',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowRoute = EscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const FxRoute = FxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => rootRouteImport,
} as any)
const ImporterRoute = ImporterRouteImport.update({
  id: '/importer',
  path: '/importer',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const KybOnboardingRoute = KybOnboardingRouteImport.update({
  id: '/kyb-onboarding',
  path: '/kyb-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LandedCostRoute = LandedCostRouteImport.update({
  id: '/landed-cost',
  path: '/landed-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MySuppliersRoute = MySuppliersRouteImport.update({
  id: '/my-suppliers',
  path: '/my-suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PayersRoute = PayersRouteImport.update({
  id: '/payers',
  path: '/payers',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentLinksRoute = PaymentLinksRouteImport.update({
  id: '/payment-links',
  path: '/payment-links',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierPortalRoute = SupplierPortalRouteImport.update({
  id: '/supplier-portal',
  path: '/supplier-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeDeskRoute = TradeDeskRouteImport.update({
  id: '/trade-desk',
  path: '/trade-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeNetworkRoute = TradeNetworkRouteImport.update({
  id: '/trade-network',
  path: '/trade-network',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const UserStoriesRoute = UserStoriesRouteImport.update({
  id: '/user-stories',
  path: '/user-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationCenterRoute = VerificationCenterRouteImport.update({
  id: '/verification-center',
  path: '/verification-center',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedBuyersRoute = VerifiedBuyersRouteImport.update({
  id: '/verified-buyers',
  path: '/verified-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedSuppliersRoute = VerifiedSuppliersRouteImport.update({
  id: '/verified-suppliers',
  path: '/verified-suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsNewRoute = CollectionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CollectionsRoute,
} as any)
const ImporterCardsRoute = ImporterCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => ImporterRoute,
} as any)
const MerchantKybRoute = MerchantKybRouteImport.update({
  id: '/merchant/kyb',
  path: '/merchant/kyb',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantProfileRoute = MerchantProfileRouteImport.update({
  id: '/merchant/profile',
  path: '/merchant/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PLinkIdRoute = PLinkIdRouteImport.update({
  id: '/p/$linkId',
  path: '/p/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerActivityLogRoute = PartnerActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerCasesRoute = PartnerCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerClientsRoute = PartnerClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerCommissionsRoute = PartnerCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerDisputesRoute = PartnerDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerDocumentsRoute = PartnerDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerFxQuotesRoute = PartnerFxQuotesRouteImport.update({
  id: '/fx-quotes',
  path: '/fx-quotes',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerLeadsRoute = PartnerLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerMarketersRoute = PartnerMarketersRouteImport.update({
  id: '/marketers',
  path: '/marketers',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerNewReferralRoute = PartnerNewReferralRouteImport.update({
  id: '/new-referral',
  path: '/new-referral',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerPaymentLinksRoute = PartnerPaymentLinksRouteImport.update({
  id: '/payment-links',
  path: '/payment-links',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerPayoutsRoute = PartnerPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerReportsRoute = PartnerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerSettingsRoute = PartnerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerSolicitorsRoute = PartnerSolicitorsRouteImport.update({
  id: '/solicitors',
  path: '/solicitors',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerTeamRoute = PartnerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => PartnerRoute,
} as any)
const PayLinkIdRoute = PayLinkIdRouteImport.update({
  id: '/pay/$linkId',
  path: '/pay/$linkId',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierPortalIndexRoute = SupplierPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalBuyersRoute = SupplierPortalBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalCreateInvoiceRoute =
  SupplierPortalCreateInvoiceRouteImport.update({
    id: '/create-invoice',
    path: '/create-invoice',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalDocumentsRoute = SupplierPortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalFxQuotesRoute = SupplierPortalFxQuotesRouteImport.update({
  id: '/fx-quotes',
  path: '/fx-quotes',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalInvoicesRoute = SupplierPortalInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalMessagesRoute = SupplierPortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalNgnBalanceRoute =
  SupplierPortalNgnBalanceRouteImport.update({
    id: '/ngn-balance',
    path: '/ngn-balance',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalNgnDetailsRoute =
  SupplierPortalNgnDetailsRouteImport.update({
    id: '/ngn-details',
    path: '/ngn-details',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalPaymentRequestsRoute =
  SupplierPortalPaymentRequestsRouteImport.update({
    id: '/payment-requests',
    path: '/payment-requests',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalPayoutAccountsRoute =
  SupplierPortalPayoutAccountsRouteImport.update({
    id: '/payout-accounts',
    path: '/payout-accounts',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalProfileRoute = SupplierPortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalReportsRoute = SupplierPortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalRequestsRoute = SupplierPortalRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalRmbBankAccountRoute =
  SupplierPortalRmbBankAccountRouteImport.update({
    id: '/rmb-bank-account',
    path: '/rmb-bank-account',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalRmbWalletRoute = SupplierPortalRmbWalletRouteImport.update({
  id: '/rmb-wallet',
  path: '/rmb-wallet',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalSettingsRoute = SupplierPortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalSettlementRoute =
  SupplierPortalSettlementRouteImport.update({
    id: '/settlement',
    path: '/settlement',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalSettlementsRoute =
  SupplierPortalSettlementsRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalSupportRoute = SupplierPortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalTeamRoute = SupplierPortalTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SupplierPortalTradeFilesRoute =
  SupplierPortalTradeFilesRouteImport.update({
    id: '/trade-files',
    path: '/trade-files',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalVerificationRoute =
  SupplierPortalVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => SupplierPortalRoute,
  } as any)
const SupplierPortalWalletRoute = SupplierPortalWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => SupplierPortalRoute,
} as any)
const SuppliersKybRoute = SuppliersKybRouteImport.update({
  id: '/kyb',
  path: '/kyb',
  getParentRoute: () => SuppliersRoute,
} as any)
const SuppliersProfileRoute = SuppliersProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SuppliersRoute,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackWhatsappRoute = TrackWhatsappRouteImport.update({
  id: '/track/whatsapp',
  path: '/track/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeDeskIndexRoute = TradeDeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TradeDeskRoute,
} as any)
const TradeDeskFileIdRoute = TradeDeskFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => TradeDeskRoute,
} as any)
const TreasuryCardsRoute = TreasuryCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => TreasuryRoute,
} as any)
const PartnerCasesIndexRoute = PartnerCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerCasesRoute,
} as any)
const PartnerCasesCaseIdRoute = PartnerCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => PartnerCasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-document-extraction': typeof AiDocumentExtractionRoute
  '/ai-growth': typeof AiGrowthRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/buyers': typeof BuyersRoute
  '/cards': typeof CardsRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/data-model': typeof DataModelRoute
  '/docs': typeof DocsRoute
  '/documents': typeof DocumentsRoute
  '/escrow': typeof EscrowRoute
  '/fx': typeof FxRoute
  '/importer': typeof ImporterRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/kyb-onboarding': typeof KybOnboardingRoute
  '/landed-cost': typeof LandedCostRoute
  '/messages': typeof MessagesRoute
  '/my-suppliers': typeof MySuppliersRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRoute
  '/organization': typeof OrganizationRoute
  '/partner': typeof PartnerRouteWithChildren
  '/payers': typeof PayersRoute
  '/payment-links': typeof PaymentLinksRoute
  '/payments': typeof PaymentsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/supplier-portal': typeof SupplierPortalRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/trade-desk': typeof TradeDeskRouteWithChildren
  '/trade-network': typeof TradeNetworkRoute
  '/transactions': typeof TransactionsRoute
  '/treasury': typeof TreasuryRouteWithChildren
  '/user-stories': typeof UserStoriesRoute
  '/verification': typeof VerificationRoute
  '/verification-center': typeof VerificationCenterRoute
  '/verified-buyers': typeof VerifiedBuyersRoute
  '/verified-suppliers': typeof VerifiedSuppliersRoute
  '/wallets': typeof WalletsRoute
  '/welcome': typeof WelcomeRoute
  '/whatsapp': typeof WhatsappRoute
  '/collections/new': typeof CollectionsNewRoute
  '/importer/cards': typeof ImporterCardsRoute
  '/merchant/kyb': typeof MerchantKybRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/p/$linkId': typeof PLinkIdRoute
  '/partner/activity-log': typeof PartnerActivityLogRoute
  '/partner/cases': typeof PartnerCasesRouteWithChildren
  '/partner/clients': typeof PartnerClientsRoute
  '/partner/commissions': typeof PartnerCommissionsRoute
  '/partner/disputes': typeof PartnerDisputesRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/fx-quotes': typeof PartnerFxQuotesRoute
  '/partner/leads': typeof PartnerLeadsRoute
  '/partner/marketers': typeof PartnerMarketersRoute
  '/partner/new-referral': typeof PartnerNewReferralRoute
  '/partner/payment-links': typeof PartnerPaymentLinksRoute
  '/partner/payouts': typeof PartnerPayoutsRoute
  '/partner/reports': typeof PartnerReportsRoute
  '/partner/settings': typeof PartnerSettingsRoute
  '/partner/solicitors': typeof PartnerSolicitorsRoute
  '/partner/team': typeof PartnerTeamRoute
  '/pay/$linkId': typeof PayLinkIdRoute
  '/supplier-portal/buyers': typeof SupplierPortalBuyersRoute
  '/supplier-portal/create-invoice': typeof SupplierPortalCreateInvoiceRoute
  '/supplier-portal/documents': typeof SupplierPortalDocumentsRoute
  '/supplier-portal/fx-quotes': typeof SupplierPortalFxQuotesRoute
  '/supplier-portal/invoices': typeof SupplierPortalInvoicesRoute
  '/supplier-portal/messages': typeof SupplierPortalMessagesRoute
  '/supplier-portal/ngn-balance': typeof SupplierPortalNgnBalanceRoute
  '/supplier-portal/ngn-details': typeof SupplierPortalNgnDetailsRoute
  '/supplier-portal/payment-requests': typeof SupplierPortalPaymentRequestsRoute
  '/supplier-portal/payout-accounts': typeof SupplierPortalPayoutAccountsRoute
  '/supplier-portal/profile': typeof SupplierPortalProfileRoute
  '/supplier-portal/reports': typeof SupplierPortalReportsRoute
  '/supplier-portal/requests': typeof SupplierPortalRequestsRoute
  '/supplier-portal/rmb-bank-account': typeof SupplierPortalRmbBankAccountRoute
  '/supplier-portal/rmb-wallet': typeof SupplierPortalRmbWalletRoute
  '/supplier-portal/settings': typeof SupplierPortalSettingsRoute
  '/supplier-portal/settlement': typeof SupplierPortalSettlementRoute
  '/supplier-portal/settlements': typeof SupplierPortalSettlementsRoute
  '/supplier-portal/support': typeof SupplierPortalSupportRoute
  '/supplier-portal/team': typeof SupplierPortalTeamRoute
  '/supplier-portal/trade-files': typeof SupplierPortalTradeFilesRoute
  '/supplier-portal/verification': typeof SupplierPortalVerificationRoute
  '/supplier-portal/wallet': typeof SupplierPortalWalletRoute
  '/suppliers/kyb': typeof SuppliersKybRoute
  '/suppliers/profile': typeof SuppliersProfileRoute
  '/track/$id': typeof TrackIdRoute
  '/track/whatsapp': typeof TrackWhatsappRoute
  '/trade-desk/$fileId': typeof TradeDeskFileIdRoute
  '/treasury/cards': typeof TreasuryCardsRoute
  '/partner/': typeof PartnerIndexRoute
  '/supplier-portal/': typeof SupplierPortalIndexRoute
  '/track/': typeof TrackIndexRoute
  '/trade-desk/': typeof TradeDeskIndexRoute
  '/partner/cases/$caseId': typeof PartnerCasesCaseIdRoute
  '/partner/cases/': typeof PartnerCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-document-extraction': typeof AiDocumentExtractionRoute
  '/ai-growth': typeof AiGrowthRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/buyers': typeof BuyersRoute
  '/cards': typeof CardsRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/data-model': typeof DataModelRoute
  '/docs': typeof DocsRoute
  '/documents': typeof DocumentsRoute
  '/escrow': typeof EscrowRoute
  '/fx': typeof FxRoute
  '/importer': typeof ImporterRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/kyb-onboarding': typeof KybOnboardingRoute
  '/landed-cost': typeof LandedCostRoute
  '/messages': typeof MessagesRoute
  '/my-suppliers': typeof MySuppliersRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRoute
  '/organization': typeof OrganizationRoute
  '/payers': typeof PayersRoute
  '/payment-links': typeof PaymentLinksRoute
  '/payments': typeof PaymentsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/suppliers': typeof SuppliersRouteWithChildren
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/trade-network': typeof TradeNetworkRoute
  '/transactions': typeof TransactionsRoute
  '/treasury': typeof TreasuryRouteWithChildren
  '/user-stories': typeof UserStoriesRoute
  '/verification': typeof VerificationRoute
  '/verification-center': typeof VerificationCenterRoute
  '/verified-buyers': typeof VerifiedBuyersRoute
  '/verified-suppliers': typeof VerifiedSuppliersRoute
  '/wallets': typeof WalletsRoute
  '/welcome': typeof WelcomeRoute
  '/whatsapp': typeof WhatsappRoute
  '/collections/new': typeof CollectionsNewRoute
  '/importer/cards': typeof ImporterCardsRoute
  '/merchant/kyb': typeof MerchantKybRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/p/$linkId': typeof PLinkIdRoute
  '/partner/activity-log': typeof PartnerActivityLogRoute
  '/partner/clients': typeof PartnerClientsRoute
  '/partner/commissions': typeof PartnerCommissionsRoute
  '/partner/disputes': typeof PartnerDisputesRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/fx-quotes': typeof PartnerFxQuotesRoute
  '/partner/leads': typeof PartnerLeadsRoute
  '/partner/marketers': typeof PartnerMarketersRoute
  '/partner/new-referral': typeof PartnerNewReferralRoute
  '/partner/payment-links': typeof PartnerPaymentLinksRoute
  '/partner/payouts': typeof PartnerPayoutsRoute
  '/partner/reports': typeof PartnerReportsRoute
  '/partner/settings': typeof PartnerSettingsRoute
  '/partner/solicitors': typeof PartnerSolicitorsRoute
  '/partner/team': typeof PartnerTeamRoute
  '/pay/$linkId': typeof PayLinkIdRoute
  '/supplier-portal/buyers': typeof SupplierPortalBuyersRoute
  '/supplier-portal/create-invoice': typeof SupplierPortalCreateInvoiceRoute
  '/supplier-portal/documents': typeof SupplierPortalDocumentsRoute
  '/supplier-portal/fx-quotes': typeof SupplierPortalFxQuotesRoute
  '/supplier-portal/invoices': typeof SupplierPortalInvoicesRoute
  '/supplier-portal/messages': typeof SupplierPortalMessagesRoute
  '/supplier-portal/ngn-balance': typeof SupplierPortalNgnBalanceRoute
  '/supplier-portal/ngn-details': typeof SupplierPortalNgnDetailsRoute
  '/supplier-portal/payment-requests': typeof SupplierPortalPaymentRequestsRoute
  '/supplier-portal/payout-accounts': typeof SupplierPortalPayoutAccountsRoute
  '/supplier-portal/profile': typeof SupplierPortalProfileRoute
  '/supplier-portal/reports': typeof SupplierPortalReportsRoute
  '/supplier-portal/requests': typeof SupplierPortalRequestsRoute
  '/supplier-portal/rmb-bank-account': typeof SupplierPortalRmbBankAccountRoute
  '/supplier-portal/rmb-wallet': typeof SupplierPortalRmbWalletRoute
  '/supplier-portal/settings': typeof SupplierPortalSettingsRoute
  '/supplier-portal/settlement': typeof SupplierPortalSettlementRoute
  '/supplier-portal/settlements': typeof SupplierPortalSettlementsRoute
  '/supplier-portal/support': typeof SupplierPortalSupportRoute
  '/supplier-portal/team': typeof SupplierPortalTeamRoute
  '/supplier-portal/trade-files': typeof SupplierPortalTradeFilesRoute
  '/supplier-portal/verification': typeof SupplierPortalVerificationRoute
  '/supplier-portal/wallet': typeof SupplierPortalWalletRoute
  '/suppliers/kyb': typeof SuppliersKybRoute
  '/suppliers/profile': typeof SuppliersProfileRoute
  '/track/$id': typeof TrackIdRoute
  '/track/whatsapp': typeof TrackWhatsappRoute
  '/trade-desk/$fileId': typeof TradeDeskFileIdRoute
  '/treasury/cards': typeof TreasuryCardsRoute
  '/partner': typeof PartnerIndexRoute
  '/supplier-portal': typeof SupplierPortalIndexRoute
  '/track': typeof TrackIndexRoute
  '/trade-desk': typeof TradeDeskIndexRoute
  '/partner/cases/$caseId': typeof PartnerCasesCaseIdRoute
  '/partner/cases': typeof PartnerCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-document-extraction': typeof AiDocumentExtractionRoute
  '/ai-growth': typeof AiGrowthRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/buyers': typeof BuyersRoute
  '/cards': typeof CardsRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/data-model': typeof DataModelRoute
  '/docs': typeof DocsRoute
  '/documents': typeof DocumentsRoute
  '/escrow': typeof EscrowRoute
  '/fx': typeof FxRoute
  '/importer': typeof ImporterRouteWithChildren
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/kyb-onboarding': typeof KybOnboardingRoute
  '/landed-cost': typeof LandedCostRoute
  '/messages': typeof MessagesRoute
  '/my-suppliers': typeof MySuppliersRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRoute
  '/organization': typeof OrganizationRoute
  '/partner': typeof PartnerRouteWithChildren
  '/payers': typeof PayersRoute
  '/payment-links': typeof PaymentLinksRoute
  '/payments': typeof PaymentsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/supplier-portal': typeof SupplierPortalRouteWithChildren
  '/suppliers': typeof SuppliersRouteWithChildren
  '/support': typeof SupportRoute
  '/team': typeof TeamRoute
  '/trade-desk': typeof TradeDeskRouteWithChildren
  '/trade-network': typeof TradeNetworkRoute
  '/transactions': typeof TransactionsRoute
  '/treasury': typeof TreasuryRouteWithChildren
  '/user-stories': typeof UserStoriesRoute
  '/verification': typeof VerificationRoute
  '/verification-center': typeof VerificationCenterRoute
  '/verified-buyers': typeof VerifiedBuyersRoute
  '/verified-suppliers': typeof VerifiedSuppliersRoute
  '/wallets': typeof WalletsRoute
  '/welcome': typeof WelcomeRoute
  '/whatsapp': typeof WhatsappRoute
  '/collections/new': typeof CollectionsNewRoute
  '/importer/cards': typeof ImporterCardsRoute
  '/merchant/kyb': typeof MerchantKybRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/p/$linkId': typeof PLinkIdRoute
  '/partner/activity-log': typeof PartnerActivityLogRoute
  '/partner/cases': typeof PartnerCasesRouteWithChildren
  '/partner/clients': typeof PartnerClientsRoute
  '/partner/commissions': typeof PartnerCommissionsRoute
  '/partner/disputes': typeof PartnerDisputesRoute
  '/partner/documents': typeof PartnerDocumentsRoute
  '/partner/fx-quotes': typeof PartnerFxQuotesRoute
  '/partner/leads': typeof PartnerLeadsRoute
  '/partner/marketers': typeof PartnerMarketersRoute
  '/partner/new-referral': typeof PartnerNewReferralRoute
  '/partner/payment-links': typeof PartnerPaymentLinksRoute
  '/partner/payouts': typeof PartnerPayoutsRoute
  '/partner/reports': typeof PartnerReportsRoute
  '/partner/settings': typeof PartnerSettingsRoute
  '/partner/solicitors': typeof PartnerSolicitorsRoute
  '/partner/team': typeof PartnerTeamRoute
  '/pay/$linkId': typeof PayLinkIdRoute
  '/supplier-portal/buyers': typeof SupplierPortalBuyersRoute
  '/supplier-portal/create-invoice': typeof SupplierPortalCreateInvoiceRoute
  '/supplier-portal/documents': typeof SupplierPortalDocumentsRoute
  '/supplier-portal/fx-quotes': typeof SupplierPortalFxQuotesRoute
  '/supplier-portal/invoices': typeof SupplierPortalInvoicesRoute
  '/supplier-portal/messages': typeof SupplierPortalMessagesRoute
  '/supplier-portal/ngn-balance': typeof SupplierPortalNgnBalanceRoute
  '/supplier-portal/ngn-details': typeof SupplierPortalNgnDetailsRoute
  '/supplier-portal/payment-requests': typeof SupplierPortalPaymentRequestsRoute
  '/supplier-portal/payout-accounts': typeof SupplierPortalPayoutAccountsRoute
  '/supplier-portal/profile': typeof SupplierPortalProfileRoute
  '/supplier-portal/reports': typeof SupplierPortalReportsRoute
  '/supplier-portal/requests': typeof SupplierPortalRequestsRoute
  '/supplier-portal/rmb-bank-account': typeof SupplierPortalRmbBankAccountRoute
  '/supplier-portal/rmb-wallet': typeof SupplierPortalRmbWalletRoute
  '/supplier-portal/settings': typeof SupplierPortalSettingsRoute
  '/supplier-portal/settlement': typeof SupplierPortalSettlementRoute
  '/supplier-portal/settlements': typeof SupplierPortalSettlementsRoute
  '/supplier-portal/support': typeof SupplierPortalSupportRoute
  '/supplier-portal/team': typeof SupplierPortalTeamRoute
  '/supplier-portal/trade-files': typeof SupplierPortalTradeFilesRoute
  '/supplier-portal/verification': typeof SupplierPortalVerificationRoute
  '/supplier-portal/wallet': typeof SupplierPortalWalletRoute
  '/suppliers/kyb': typeof SuppliersKybRoute
  '/suppliers/profile': typeof SuppliersProfileRoute
  '/track/$id': typeof TrackIdRoute
  '/track/whatsapp': typeof TrackWhatsappRoute
  '/trade-desk/$fileId': typeof TradeDeskFileIdRoute
  '/treasury/cards': typeof TreasuryCardsRoute
  '/partner/': typeof PartnerIndexRoute
  '/supplier-portal/': typeof SupplierPortalIndexRoute
  '/track/': typeof TrackIndexRoute
  '/trade-desk/': typeof TradeDeskIndexRoute
  '/partner/cases/$caseId': typeof PartnerCasesCaseIdRoute
  '/partner/cases/': typeof PartnerCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-document-extraction'
    | '/ai-growth'
    | '/ai-insights'
    | '/approvals'
    | '/audit-logs'
    | '/beneficiaries'
    | '/buyers'
    | '/cards'
    | '/collections'
    | '/compliance'
    | '/customers'
    | '/dashboard'
    | '/data-model'
    | '/docs'
    | '/documents'
    | '/escrow'
    | '/fx'
    | '/importer'
    | '/integrations'
    | '/invoices'
    | '/kyb-onboarding'
    | '/landed-cost'
    | '/messages'
    | '/my-suppliers'
    | '/onboarding'
    | '/ops'
    | '/organization'
    | '/partner'
    | '/payers'
    | '/payment-links'
    | '/payments'
    | '/reconciliation'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/supplier-portal'
    | '/suppliers'
    | '/support'
    | '/team'
    | '/trade-desk'
    | '/trade-network'
    | '/transactions'
    | '/treasury'
    | '/user-stories'
    | '/verification'
    | '/verification-center'
    | '/verified-buyers'
    | '/verified-suppliers'
    | '/wallets'
    | '/welcome'
    | '/whatsapp'
    | '/collections/new'
    | '/importer/cards'
    | '/merchant/kyb'
    | '/merchant/profile'
    | '/p/$linkId'
    | '/partner/activity-log'
    | '/partner/cases'
    | '/partner/clients'
    | '/partner/commissions'
    | '/partner/disputes'
    | '/partner/documents'
    | '/partner/fx-quotes'
    | '/partner/leads'
    | '/partner/marketers'
    | '/partner/new-referral'
    | '/partner/payment-links'
    | '/partner/payouts'
    | '/partner/reports'
    | '/partner/settings'
    | '/partner/solicitors'
    | '/partner/team'
    | '/pay/$linkId'
    | '/supplier-portal/buyers'
    | '/supplier-portal/create-invoice'
    | '/supplier-portal/documents'
    | '/supplier-portal/fx-quotes'
    | '/supplier-portal/invoices'
    | '/supplier-portal/messages'
    | '/supplier-portal/ngn-balance'
    | '/supplier-portal/ngn-details'
    | '/supplier-portal/payment-requests'
    | '/supplier-portal/payout-accounts'
    | '/supplier-portal/profile'
    | '/supplier-portal/reports'
    | '/supplier-portal/requests'
    | '/supplier-portal/rmb-bank-account'
    | '/supplier-portal/rmb-wallet'
    | '/supplier-portal/settings'
    | '/supplier-portal/settlement'
    | '/supplier-portal/settlements'
    | '/supplier-portal/support'
    | '/supplier-portal/team'
    | '/supplier-portal/trade-files'
    | '/supplier-portal/verification'
    | '/supplier-portal/wallet'
    | '/suppliers/kyb'
    | '/suppliers/profile'
    | '/track/$id'
    | '/track/whatsapp'
    | '/trade-desk/$fileId'
    | '/treasury/cards'
    | '/partner/'
    | '/supplier-portal/'
    | '/track/'
    | '/trade-desk/'
    | '/partner/cases/$caseId'
    | '/partner/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-document-extraction'
    | '/ai-growth'
    | '/ai-insights'
    | '/approvals'
    | '/audit-logs'
    | '/beneficiaries'
    | '/buyers'
    | '/cards'
    | '/collections'
    | '/compliance'
    | '/customers'
    | '/dashboard'
    | '/data-model'
    | '/docs'
    | '/documents'
    | '/escrow'
    | '/fx'
    | '/importer'
    | '/integrations'
    | '/invoices'
    | '/kyb-onboarding'
    | '/landed-cost'
    | '/messages'
    | '/my-suppliers'
    | '/onboarding'
    | '/ops'
    | '/organization'
    | '/payers'
    | '/payment-links'
    | '/payments'
    | '/reconciliation'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/suppliers'
    | '/support'
    | '/team'
    | '/trade-network'
    | '/transactions'
    | '/treasury'
    | '/user-stories'
    | '/verification'
    | '/verification-center'
    | '/verified-buyers'
    | '/verified-suppliers'
    | '/wallets'
    | '/welcome'
    | '/whatsapp'
    | '/collections/new'
    | '/importer/cards'
    | '/merchant/kyb'
    | '/merchant/profile'
    | '/p/$linkId'
    | '/partner/activity-log'
    | '/partner/clients'
    | '/partner/commissions'
    | '/partner/disputes'
    | '/partner/documents'
    | '/partner/fx-quotes'
    | '/partner/leads'
    | '/partner/marketers'
    | '/partner/new-referral'
    | '/partner/payment-links'
    | '/partner/payouts'
    | '/partner/reports'
    | '/partner/settings'
    | '/partner/solicitors'
    | '/partner/team'
    | '/pay/$linkId'
    | '/supplier-portal/buyers'
    | '/supplier-portal/create-invoice'
    | '/supplier-portal/documents'
    | '/supplier-portal/fx-quotes'
    | '/supplier-portal/invoices'
    | '/supplier-portal/messages'
    | '/supplier-portal/ngn-balance'
    | '/supplier-portal/ngn-details'
    | '/supplier-portal/payment-requests'
    | '/supplier-portal/payout-accounts'
    | '/supplier-portal/profile'
    | '/supplier-portal/reports'
    | '/supplier-portal/requests'
    | '/supplier-portal/rmb-bank-account'
    | '/supplier-portal/rmb-wallet'
    | '/supplier-portal/settings'
    | '/supplier-portal/settlement'
    | '/supplier-portal/settlements'
    | '/supplier-portal/support'
    | '/supplier-portal/team'
    | '/supplier-portal/trade-files'
    | '/supplier-portal/verification'
    | '/supplier-portal/wallet'
    | '/suppliers/kyb'
    | '/suppliers/profile'
    | '/track/$id'
    | '/track/whatsapp'
    | '/trade-desk/$fileId'
    | '/treasury/cards'
    | '/partner'
    | '/supplier-portal'
    | '/track'
    | '/trade-desk'
    | '/partner/cases/$caseId'
    | '/partner/cases'
  id:
    | '__root__'
    | '/'
    | '/ai-document-extraction'
    | '/ai-growth'
    | '/ai-insights'
    | '/approvals'
    | '/audit-logs'
    | '/beneficiaries'
    | '/buyers'
    | '/cards'
    | '/collections'
    | '/compliance'
    | '/customers'
    | '/dashboard'
    | '/data-model'
    | '/docs'
    | '/documents'
    | '/escrow'
    | '/fx'
    | '/importer'
    | '/integrations'
    | '/invoices'
    | '/kyb-onboarding'
    | '/landed-cost'
    | '/messages'
    | '/my-suppliers'
    | '/onboarding'
    | '/ops'
    | '/organization'
    | '/partner'
    | '/payers'
    | '/payment-links'
    | '/payments'
    | '/reconciliation'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/supplier-portal'
    | '/suppliers'
    | '/support'
    | '/team'
    | '/trade-desk'
    | '/trade-network'
    | '/transactions'
    | '/treasury'
    | '/user-stories'
    | '/verification'
    | '/verification-center'
    | '/verified-buyers'
    | '/verified-suppliers'
    | '/wallets'
    | '/welcome'
    | '/whatsapp'
    | '/collections/new'
    | '/importer/cards'
    | '/merchant/kyb'
    | '/merchant/profile'
    | '/p/$linkId'
    | '/partner/activity-log'
    | '/partner/cases'
    | '/partner/clients'
    | '/partner/commissions'
    | '/partner/disputes'
    | '/partner/documents'
    | '/partner/fx-quotes'
    | '/partner/leads'
    | '/partner/marketers'
    | '/partner/new-referral'
    | '/partner/payment-links'
    | '/partner/payouts'
    | '/partner/reports'
    | '/partner/settings'
    | '/partner/solicitors'
    | '/partner/team'
    | '/pay/$linkId'
    | '/supplier-portal/buyers'
    | '/supplier-portal/create-invoice'
    | '/supplier-portal/documents'
    | '/supplier-portal/fx-quotes'
    | '/supplier-portal/invoices'
    | '/supplier-portal/messages'
    | '/supplier-portal/ngn-balance'
    | '/supplier-portal/ngn-details'
    | '/supplier-portal/payment-requests'
    | '/supplier-portal/payout-accounts'
    | '/supplier-portal/profile'
    | '/supplier-portal/reports'
    | '/supplier-portal/requests'
    | '/supplier-portal/rmb-bank-account'
    | '/supplier-portal/rmb-wallet'
    | '/supplier-portal/settings'
    | '/supplier-portal/settlement'
    | '/supplier-portal/settlements'
    | '/supplier-portal/support'
    | '/supplier-portal/team'
    | '/supplier-portal/trade-files'
    | '/supplier-portal/verification'
    | '/supplier-portal/wallet'
    | '/suppliers/kyb'
    | '/suppliers/profile'
    | '/track/$id'
    | '/track/whatsapp'
    | '/trade-desk/$fileId'
    | '/treasury/cards'
    | '/partner/'
    | '/supplier-portal/'
    | '/track/'
    | '/trade-desk/'
    | '/partner/cases/$caseId'
    | '/partner/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDocumentExtractionRoute: typeof AiDocumentExtractionRoute
  AiGrowthRoute: typeof AiGrowthRoute
  AiInsightsRoute: typeof AiInsightsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BeneficiariesRoute: typeof BeneficiariesRoute
  BuyersRoute: typeof BuyersRoute
  CardsRoute: typeof CardsRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ComplianceRoute: typeof ComplianceRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DataModelRoute: typeof DataModelRoute
  DocsRoute: typeof DocsRoute
  DocumentsRoute: typeof DocumentsRoute
  EscrowRoute: typeof EscrowRoute
  FxRoute: typeof FxRoute
  ImporterRoute: typeof ImporterRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRoute
  InvoicesRoute: typeof InvoicesRoute
  KybOnboardingRoute: typeof KybOnboardingRoute
  LandedCostRoute: typeof LandedCostRoute
  MessagesRoute: typeof MessagesRoute
  MySuppliersRoute: typeof MySuppliersRoute
  OnboardingRoute: typeof OnboardingRoute
  OpsRoute: typeof OpsRoute
  OrganizationRoute: typeof OrganizationRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PayersRoute: typeof PayersRoute
  PaymentLinksRoute: typeof PaymentLinksRoute
  PaymentsRoute: typeof PaymentsRoute
  ReconciliationRoute: typeof ReconciliationRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  SupplierPortalRoute: typeof SupplierPortalRouteWithChildren
  SuppliersRoute: typeof SuppliersRouteWithChildren
  SupportRoute: typeof SupportRoute
  TeamRoute: typeof TeamRoute
  TradeDeskRoute: typeof TradeDeskRouteWithChildren
  TradeNetworkRoute: typeof TradeNetworkRoute
  TransactionsRoute: typeof TransactionsRoute
  TreasuryRoute: typeof TreasuryRouteWithChildren
  UserStoriesRoute: typeof UserStoriesRoute
  VerificationRoute: typeof VerificationRoute
  VerificationCenterRoute: typeof VerificationCenterRoute
  VerifiedBuyersRoute: typeof VerifiedBuyersRoute
  VerifiedSuppliersRoute: typeof VerifiedSuppliersRoute
  WalletsRoute: typeof WalletsRoute
  WelcomeRoute: typeof WelcomeRoute
  WhatsappRoute: typeof WhatsappRoute
  MerchantKybRoute: typeof MerchantKybRoute
  MerchantProfileRoute: typeof MerchantProfileRoute
  PLinkIdRoute: typeof PLinkIdRoute
  PayLinkIdRoute: typeof PayLinkIdRoute
  TrackIdRoute: typeof TrackIdRoute
  TrackWhatsappRoute: typeof TrackWhatsappRoute
  TrackIndexRoute: typeof TrackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-document-extraction': {
      id: '/ai-document-extraction'
      path: '/ai-document-extraction'
      fullPath: '/ai-document-extraction'
      preLoaderRoute: typeof AiDocumentExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-growth': {
      id: '/ai-growth'
      path: '/ai-growth'
      fullPath: '/ai-growth'
      preLoaderRoute: typeof AiGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries': {
      id: '/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof BeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-model': {
      id: '/data-model'
      path: '/data-model'
      fullPath: '/data-model'
      preLoaderRoute: typeof DataModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow': {
      id: '/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof EscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx': {
      id: '/fx'
      path: '/fx'
      fullPath: '/fx'
      preLoaderRoute: typeof FxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importer': {
      id: '/importer'
      path: '/importer'
      fullPath: '/importer'
      preLoaderRoute: typeof ImporterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyb-onboarding': {
      id: '/kyb-onboarding'
      path: '/kyb-onboarding'
      fullPath: '/kyb-onboarding'
      preLoaderRoute: typeof KybOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landed-cost': {
      id: '/landed-cost'
      path: '/landed-cost'
      fullPath: '/landed-cost'
      preLoaderRoute: typeof LandedCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-suppliers': {
      id: '/my-suppliers'
      path: '/my-suppliers'
      fullPath: '/my-suppliers'
      preLoaderRoute: typeof MySuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payers': {
      id: '/payers'
      path: '/payers'
      fullPath: '/payers'
      preLoaderRoute: typeof PayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-links': {
      id: '/payment-links'
      path: '/payment-links'
      fullPath: '/payment-links'
      preLoaderRoute: typeof PaymentLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-portal': {
      id: '/supplier-portal'
      path: '/supplier-portal'
      fullPath: '/supplier-portal'
      preLoaderRoute: typeof SupplierPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-desk': {
      id: '/trade-desk'
      path: '/trade-desk'
      fullPath: '/trade-desk'
      preLoaderRoute: typeof TradeDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-network': {
      id: '/trade-network'
      path: '/trade-network'
      fullPath: '/trade-network'
      preLoaderRoute: typeof TradeNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-stories': {
      id: '/user-stories'
      path: '/user-stories'
      fullPath: '/user-stories'
      preLoaderRoute: typeof UserStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-center': {
      id: '/verification-center'
      path: '/verification-center'
      fullPath: '/verification-center'
      preLoaderRoute: typeof VerificationCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified-buyers': {
      id: '/verified-buyers'
      path: '/verified-buyers'
      fullPath: '/verified-buyers'
      preLoaderRoute: typeof VerifiedBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified-suppliers': {
      id: '/verified-suppliers'
      path: '/verified-suppliers'
      fullPath: '/verified-suppliers'
      preLoaderRoute: typeof VerifiedSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/new': {
      id: '/collections/new'
      path: '/new'
      fullPath: '/collections/new'
      preLoaderRoute: typeof CollectionsNewRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/importer/cards': {
      id: '/importer/cards'
      path: '/cards'
      fullPath: '/importer/cards'
      preLoaderRoute: typeof ImporterCardsRouteImport
      parentRoute: typeof ImporterRoute
    }
    '/merchant/kyb': {
      id: '/merchant/kyb'
      path: '/merchant/kyb'
      fullPath: '/merchant/kyb'
      preLoaderRoute: typeof MerchantKybRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/profile': {
      id: '/merchant/profile'
      path: '/merchant/profile'
      fullPath: '/merchant/profile'
      preLoaderRoute: typeof MerchantProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$linkId': {
      id: '/p/$linkId'
      path: '/p/$linkId'
      fullPath: '/p/$linkId'
      preLoaderRoute: typeof PLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/activity-log': {
      id: '/partner/activity-log'
      path: '/activity-log'
      fullPath: '/partner/activity-log'
      preLoaderRoute: typeof PartnerActivityLogRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/cases': {
      id: '/partner/cases'
      path: '/cases'
      fullPath: '/partner/cases'
      preLoaderRoute: typeof PartnerCasesRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/clients': {
      id: '/partner/clients'
      path: '/clients'
      fullPath: '/partner/clients'
      preLoaderRoute: typeof PartnerClientsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/commissions': {
      id: '/partner/commissions'
      path: '/commissions'
      fullPath: '/partner/commissions'
      preLoaderRoute: typeof PartnerCommissionsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/disputes': {
      id: '/partner/disputes'
      path: '/disputes'
      fullPath: '/partner/disputes'
      preLoaderRoute: typeof PartnerDisputesRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/documents': {
      id: '/partner/documents'
      path: '/documents'
      fullPath: '/partner/documents'
      preLoaderRoute: typeof PartnerDocumentsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/fx-quotes': {
      id: '/partner/fx-quotes'
      path: '/fx-quotes'
      fullPath: '/partner/fx-quotes'
      preLoaderRoute: typeof PartnerFxQuotesRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/leads': {
      id: '/partner/leads'
      path: '/leads'
      fullPath: '/partner/leads'
      preLoaderRoute: typeof PartnerLeadsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/marketers': {
      id: '/partner/marketers'
      path: '/marketers'
      fullPath: '/partner/marketers'
      preLoaderRoute: typeof PartnerMarketersRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/new-referral': {
      id: '/partner/new-referral'
      path: '/new-referral'
      fullPath: '/partner/new-referral'
      preLoaderRoute: typeof PartnerNewReferralRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/payment-links': {
      id: '/partner/payment-links'
      path: '/payment-links'
      fullPath: '/partner/payment-links'
      preLoaderRoute: typeof PartnerPaymentLinksRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/payouts': {
      id: '/partner/payouts'
      path: '/payouts'
      fullPath: '/partner/payouts'
      preLoaderRoute: typeof PartnerPayoutsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/reports': {
      id: '/partner/reports'
      path: '/reports'
      fullPath: '/partner/reports'
      preLoaderRoute: typeof PartnerReportsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/settings': {
      id: '/partner/settings'
      path: '/settings'
      fullPath: '/partner/settings'
      preLoaderRoute: typeof PartnerSettingsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/solicitors': {
      id: '/partner/solicitors'
      path: '/solicitors'
      fullPath: '/partner/solicitors'
      preLoaderRoute: typeof PartnerSolicitorsRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/team': {
      id: '/partner/team'
      path: '/team'
      fullPath: '/partner/team'
      preLoaderRoute: typeof PartnerTeamRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/pay/$linkId': {
      id: '/pay/$linkId'
      path: '/pay/$linkId'
      fullPath: '/pay/$linkId'
      preLoaderRoute: typeof PayLinkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-portal/': {
      id: '/supplier-portal/'
      path: '/'
      fullPath: '/supplier-portal/'
      preLoaderRoute: typeof SupplierPortalIndexRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/buyers': {
      id: '/supplier-portal/buyers'
      path: '/buyers'
      fullPath: '/supplier-portal/buyers'
      preLoaderRoute: typeof SupplierPortalBuyersRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/create-invoice': {
      id: '/supplier-portal/create-invoice'
      path: '/create-invoice'
      fullPath: '/supplier-portal/create-invoice'
      preLoaderRoute: typeof SupplierPortalCreateInvoiceRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/documents': {
      id: '/supplier-portal/documents'
      path: '/documents'
      fullPath: '/supplier-portal/documents'
      preLoaderRoute: typeof SupplierPortalDocumentsRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/fx-quotes': {
      id: '/supplier-portal/fx-quotes'
      path: '/fx-quotes'
      fullPath: '/supplier-portal/fx-quotes'
      preLoaderRoute: typeof SupplierPortalFxQuotesRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/invoices': {
      id: '/supplier-portal/invoices'
      path: '/invoices'
      fullPath: '/supplier-portal/invoices'
      preLoaderRoute: typeof SupplierPortalInvoicesRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/messages': {
      id: '/supplier-portal/messages'
      path: '/messages'
      fullPath: '/supplier-portal/messages'
      preLoaderRoute: typeof SupplierPortalMessagesRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/ngn-balance': {
      id: '/supplier-portal/ngn-balance'
      path: '/ngn-balance'
      fullPath: '/supplier-portal/ngn-balance'
      preLoaderRoute: typeof SupplierPortalNgnBalanceRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/ngn-details': {
      id: '/supplier-portal/ngn-details'
      path: '/ngn-details'
      fullPath: '/supplier-portal/ngn-details'
      preLoaderRoute: typeof SupplierPortalNgnDetailsRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/payment-requests': {
      id: '/supplier-portal/payment-requests'
      path: '/payment-requests'
      fullPath: '/supplier-portal/payment-requests'
      preLoaderRoute: typeof SupplierPortalPaymentRequestsRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/payout-accounts': {
      id: '/supplier-portal/payout-accounts'
      path: '/payout-accounts'
      fullPath: '/supplier-portal/payout-accounts'
      preLoaderRoute: typeof SupplierPortalPayoutAccountsRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/profile': {
      id: '/supplier-portal/profile'
      path: '/profile'
      fullPath: '/supplier-portal/profile'
      preLoaderRoute: typeof SupplierPortalProfileRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/reports': {
      id: '/supplier-portal/reports'
      path: '/reports'
      fullPath: '/supplier-portal/reports'
      preLoaderRoute: typeof SupplierPortalReportsRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/requests': {
      id: '/supplier-portal/requests'
      path: '/requests'
      fullPath: '/supplier-portal/requests'
      preLoaderRoute: typeof SupplierPortalRequestsRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/rmb-bank-account': {
      id: '/supplier-portal/rmb-bank-account'
      path: '/rmb-bank-account'
      fullPath: '/supplier-portal/rmb-bank-account'
      preLoaderRoute: typeof SupplierPortalRmbBankAccountRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/rmb-wallet': {
      id: '/supplier-portal/rmb-wallet'
      path: '/rmb-wallet'
      fullPath: '/supplier-portal/rmb-wallet'
      preLoaderRoute: typeof SupplierPortalRmbWalletRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/settings': {
      id: '/supplier-portal/settings'
      path: '/settings'
      fullPath: '/supplier-portal/settings'
      preLoaderRoute: typeof SupplierPortalSettingsRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/settlement': {
      id: '/supplier-portal/settlement'
      path: '/settlement'
      fullPath: '/supplier-portal/settlement'
      preLoaderRoute: typeof SupplierPortalSettlementRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/settlements': {
      id: '/supplier-portal/settlements'
      path: '/settlements'
      fullPath: '/supplier-portal/settlements'
      preLoaderRoute: typeof SupplierPortalSettlementsRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/support': {
      id: '/supplier-portal/support'
      path: '/support'
      fullPath: '/supplier-portal/support'
      preLoaderRoute: typeof SupplierPortalSupportRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/team': {
      id: '/supplier-portal/team'
      path: '/team'
      fullPath: '/supplier-portal/team'
      preLoaderRoute: typeof SupplierPortalTeamRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/trade-files': {
      id: '/supplier-portal/trade-files'
      path: '/trade-files'
      fullPath: '/supplier-portal/trade-files'
      preLoaderRoute: typeof SupplierPortalTradeFilesRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/verification': {
      id: '/supplier-portal/verification'
      path: '/verification'
      fullPath: '/supplier-portal/verification'
      preLoaderRoute: typeof SupplierPortalVerificationRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/supplier-portal/wallet': {
      id: '/supplier-portal/wallet'
      path: '/wallet'
      fullPath: '/supplier-portal/wallet'
      preLoaderRoute: typeof SupplierPortalWalletRouteImport
      parentRoute: typeof SupplierPortalRoute
    }
    '/suppliers/kyb': {
      id: '/suppliers/kyb'
      path: '/kyb'
      fullPath: '/suppliers/kyb'
      preLoaderRoute: typeof SuppliersKybRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/suppliers/profile': {
      id: '/suppliers/profile'
      path: '/profile'
      fullPath: '/suppliers/profile'
      preLoaderRoute: typeof SuppliersProfileRouteImport
      parentRoute: typeof SuppliersRoute
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/whatsapp': {
      id: '/track/whatsapp'
      path: '/track/whatsapp'
      fullPath: '/track/whatsapp'
      preLoaderRoute: typeof TrackWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-desk/': {
      id: '/trade-desk/'
      path: '/'
      fullPath: '/trade-desk/'
      preLoaderRoute: typeof TradeDeskIndexRouteImport
      parentRoute: typeof TradeDeskRoute
    }
    '/trade-desk/$fileId': {
      id: '/trade-desk/$fileId'
      path: '/$fileId'
      fullPath: '/trade-desk/$fileId'
      preLoaderRoute: typeof TradeDeskFileIdRouteImport
      parentRoute: typeof TradeDeskRoute
    }
    '/treasury/cards': {
      id: '/treasury/cards'
      path: '/cards'
      fullPath: '/treasury/cards'
      preLoaderRoute: typeof TreasuryCardsRouteImport
      parentRoute: typeof TreasuryRoute
    }
    '/partner/cases/': {
      id: '/partner/cases/'
      path: '/'
      fullPath: '/partner/cases/'
      preLoaderRoute: typeof PartnerCasesIndexRouteImport
      parentRoute: typeof PartnerCasesRoute
    }
    '/partner/cases/$caseId': {
      id: '/partner/cases/$caseId'
      path: '/$caseId'
      fullPath: '/partner/cases/$caseId'
      preLoaderRoute: typeof PartnerCasesCaseIdRouteImport
      parentRoute: typeof PartnerCasesRoute
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsNewRoute: typeof CollectionsNewRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsNewRoute: CollectionsNewRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface ImporterRouteChildren {
  ImporterCardsRoute: typeof ImporterCardsRoute
}

const ImporterRouteChildren: ImporterRouteChildren = {
  ImporterCardsRoute: ImporterCardsRoute,
}

const ImporterRouteWithChildren = ImporterRoute._addFileChildren(
  ImporterRouteChildren,
)

interface PartnerCasesRouteChildren {
  PartnerCasesCaseIdRoute: typeof PartnerCasesCaseIdRoute
  PartnerCasesIndexRoute: typeof PartnerCasesIndexRoute
}

const PartnerCasesRouteChildren: PartnerCasesRouteChildren = {
  PartnerCasesCaseIdRoute: PartnerCasesCaseIdRoute,
  PartnerCasesIndexRoute: PartnerCasesIndexRoute,
}

const PartnerCasesRouteWithChildren = PartnerCasesRoute._addFileChildren(
  PartnerCasesRouteChildren,
)

interface PartnerRouteChildren {
  PartnerActivityLogRoute: typeof PartnerActivityLogRoute
  PartnerCasesRoute: typeof PartnerCasesRouteWithChildren
  PartnerClientsRoute: typeof PartnerClientsRoute
  PartnerCommissionsRoute: typeof PartnerCommissionsRoute
  PartnerDisputesRoute: typeof PartnerDisputesRoute
  PartnerDocumentsRoute: typeof PartnerDocumentsRoute
  PartnerFxQuotesRoute: typeof PartnerFxQuotesRoute
  PartnerLeadsRoute: typeof PartnerLeadsRoute
  PartnerMarketersRoute: typeof PartnerMarketersRoute
  PartnerNewReferralRoute: typeof PartnerNewReferralRoute
  PartnerPaymentLinksRoute: typeof PartnerPaymentLinksRoute
  PartnerPayoutsRoute: typeof PartnerPayoutsRoute
  PartnerReportsRoute: typeof PartnerReportsRoute
  PartnerSettingsRoute: typeof PartnerSettingsRoute
  PartnerSolicitorsRoute: typeof PartnerSolicitorsRoute
  PartnerTeamRoute: typeof PartnerTeamRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerActivityLogRoute: PartnerActivityLogRoute,
  PartnerCasesRoute: PartnerCasesRouteWithChildren,
  PartnerClientsRoute: PartnerClientsRoute,
  PartnerCommissionsRoute: PartnerCommissionsRoute,
  PartnerDisputesRoute: PartnerDisputesRoute,
  PartnerDocumentsRoute: PartnerDocumentsRoute,
  PartnerFxQuotesRoute: PartnerFxQuotesRoute,
  PartnerLeadsRoute: PartnerLeadsRoute,
  PartnerMarketersRoute: PartnerMarketersRoute,
  PartnerNewReferralRoute: PartnerNewReferralRoute,
  PartnerPaymentLinksRoute: PartnerPaymentLinksRoute,
  PartnerPayoutsRoute: PartnerPayoutsRoute,
  PartnerReportsRoute: PartnerReportsRoute,
  PartnerSettingsRoute: PartnerSettingsRoute,
  PartnerSolicitorsRoute: PartnerSolicitorsRoute,
  PartnerTeamRoute: PartnerTeamRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

interface SupplierPortalRouteChildren {
  SupplierPortalBuyersRoute: typeof SupplierPortalBuyersRoute
  SupplierPortalCreateInvoiceRoute: typeof SupplierPortalCreateInvoiceRoute
  SupplierPortalDocumentsRoute: typeof SupplierPortalDocumentsRoute
  SupplierPortalFxQuotesRoute: typeof SupplierPortalFxQuotesRoute
  SupplierPortalInvoicesRoute: typeof SupplierPortalInvoicesRoute
  SupplierPortalMessagesRoute: typeof SupplierPortalMessagesRoute
  SupplierPortalNgnBalanceRoute: typeof SupplierPortalNgnBalanceRoute
  SupplierPortalNgnDetailsRoute: typeof SupplierPortalNgnDetailsRoute
  SupplierPortalPaymentRequestsRoute: typeof SupplierPortalPaymentRequestsRoute
  SupplierPortalPayoutAccountsRoute: typeof SupplierPortalPayoutAccountsRoute
  SupplierPortalProfileRoute: typeof SupplierPortalProfileRoute
  SupplierPortalReportsRoute: typeof SupplierPortalReportsRoute
  SupplierPortalRequestsRoute: typeof SupplierPortalRequestsRoute
  SupplierPortalRmbBankAccountRoute: typeof SupplierPortalRmbBankAccountRoute
  SupplierPortalRmbWalletRoute: typeof SupplierPortalRmbWalletRoute
  SupplierPortalSettingsRoute: typeof SupplierPortalSettingsRoute
  SupplierPortalSettlementRoute: typeof SupplierPortalSettlementRoute
  SupplierPortalSettlementsRoute: typeof SupplierPortalSettlementsRoute
  SupplierPortalSupportRoute: typeof SupplierPortalSupportRoute
  SupplierPortalTeamRoute: typeof SupplierPortalTeamRoute
  SupplierPortalTradeFilesRoute: typeof SupplierPortalTradeFilesRoute
  SupplierPortalVerificationRoute: typeof SupplierPortalVerificationRoute
  SupplierPortalWalletRoute: typeof SupplierPortalWalletRoute
  SupplierPortalIndexRoute: typeof SupplierPortalIndexRoute
}

const SupplierPortalRouteChildren: SupplierPortalRouteChildren = {
  SupplierPortalBuyersRoute: SupplierPortalBuyersRoute,
  SupplierPortalCreateInvoiceRoute: SupplierPortalCreateInvoiceRoute,
  SupplierPortalDocumentsRoute: SupplierPortalDocumentsRoute,
  SupplierPortalFxQuotesRoute: SupplierPortalFxQuotesRoute,
  SupplierPortalInvoicesRoute: SupplierPortalInvoicesRoute,
  SupplierPortalMessagesRoute: SupplierPortalMessagesRoute,
  SupplierPortalNgnBalanceRoute: SupplierPortalNgnBalanceRoute,
  SupplierPortalNgnDetailsRoute: SupplierPortalNgnDetailsRoute,
  SupplierPortalPaymentRequestsRoute: SupplierPortalPaymentRequestsRoute,
  SupplierPortalPayoutAccountsRoute: SupplierPortalPayoutAccountsRoute,
  SupplierPortalProfileRoute: SupplierPortalProfileRoute,
  SupplierPortalReportsRoute: SupplierPortalReportsRoute,
  SupplierPortalRequestsRoute: SupplierPortalRequestsRoute,
  SupplierPortalRmbBankAccountRoute: SupplierPortalRmbBankAccountRoute,
  SupplierPortalRmbWalletRoute: SupplierPortalRmbWalletRoute,
  SupplierPortalSettingsRoute: SupplierPortalSettingsRoute,
  SupplierPortalSettlementRoute: SupplierPortalSettlementRoute,
  SupplierPortalSettlementsRoute: SupplierPortalSettlementsRoute,
  SupplierPortalSupportRoute: SupplierPortalSupportRoute,
  SupplierPortalTeamRoute: SupplierPortalTeamRoute,
  SupplierPortalTradeFilesRoute: SupplierPortalTradeFilesRoute,
  SupplierPortalVerificationRoute: SupplierPortalVerificationRoute,
  SupplierPortalWalletRoute: SupplierPortalWalletRoute,
  SupplierPortalIndexRoute: SupplierPortalIndexRoute,
}

const SupplierPortalRouteWithChildren = SupplierPortalRoute._addFileChildren(
  SupplierPortalRouteChildren,
)

interface SuppliersRouteChildren {
  SuppliersKybRoute: typeof SuppliersKybRoute
  SuppliersProfileRoute: typeof SuppliersProfileRoute
}

const SuppliersRouteChildren: SuppliersRouteChildren = {
  SuppliersKybRoute: SuppliersKybRoute,
  SuppliersProfileRoute: SuppliersProfileRoute,
}

const SuppliersRouteWithChildren = SuppliersRoute._addFileChildren(
  SuppliersRouteChildren,
)

interface TradeDeskRouteChildren {
  TradeDeskFileIdRoute: typeof TradeDeskFileIdRoute
  TradeDeskIndexRoute: typeof TradeDeskIndexRoute
}

const TradeDeskRouteChildren: TradeDeskRouteChildren = {
  TradeDeskFileIdRoute: TradeDeskFileIdRoute,
  TradeDeskIndexRoute: TradeDeskIndexRoute,
}

const TradeDeskRouteWithChildren = TradeDeskRoute._addFileChildren(
  TradeDeskRouteChildren,
)

interface TreasuryRouteChildren {
  TreasuryCardsRoute: typeof TreasuryCardsRoute
}

const TreasuryRouteChildren: TreasuryRouteChildren = {
  TreasuryCardsRoute: TreasuryCardsRoute,
}

const TreasuryRouteWithChildren = TreasuryRoute._addFileChildren(
  TreasuryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDocumentExtractionRoute: AiDocumentExtractionRoute,
  AiGrowthRoute: AiGrowthRoute,
  AiInsightsRoute: AiInsightsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditLogsRoute: AuditLogsRoute,
  BeneficiariesRoute: BeneficiariesRoute,
  BuyersRoute: BuyersRoute,
  CardsRoute: CardsRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ComplianceRoute: ComplianceRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DataModelRoute: DataModelRoute,
  DocsRoute: DocsRoute,
  DocumentsRoute: DocumentsRoute,
  EscrowRoute: EscrowRoute,
  FxRoute: FxRoute,
  ImporterRoute: ImporterRouteWithChildren,
  IntegrationsRoute: IntegrationsRoute,
  InvoicesRoute: InvoicesRoute,
  KybOnboardingRoute: KybOnboardingRoute,
  LandedCostRoute: LandedCostRoute,
  MessagesRoute: MessagesRoute,
  MySuppliersRoute: MySuppliersRoute,
  OnboardingRoute: OnboardingRoute,
  OpsRoute: OpsRoute,
  OrganizationRoute: OrganizationRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PayersRoute: PayersRoute,
  PaymentLinksRoute: PaymentLinksRoute,
  PaymentsRoute: PaymentsRoute,
  ReconciliationRoute: ReconciliationRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRoute,
  SupplierPortalRoute: SupplierPortalRouteWithChildren,
  SuppliersRoute: SuppliersRouteWithChildren,
  SupportRoute: SupportRoute,
  TeamRoute: TeamRoute,
  TradeDeskRoute: TradeDeskRouteWithChildren,
  TradeNetworkRoute: TradeNetworkRoute,
  TransactionsRoute: TransactionsRoute,
  TreasuryRoute: TreasuryRouteWithChildren,
  UserStoriesRoute: UserStoriesRoute,
  VerificationRoute: VerificationRoute,
  VerificationCenterRoute: VerificationCenterRoute,
  VerifiedBuyersRoute: VerifiedBuyersRoute,
  VerifiedSuppliersRoute: VerifiedSuppliersRoute,
  WalletsRoute: WalletsRoute,
  WelcomeRoute: WelcomeRoute,
  WhatsappRoute: WhatsappRoute,
  MerchantKybRoute: MerchantKybRoute,
  MerchantProfileRoute: MerchantProfileRoute,
  PLinkIdRoute: PLinkIdRoute,
  PayLinkIdRoute: PayLinkIdRoute,
  TrackIdRoute: TrackIdRoute,
  TrackWhatsappRoute: TrackWhatsappRoute,
  TrackIndexRoute: TrackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
