/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as FxRouteImport } from './routes/fx'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BeneficiariesRouteImport } from './routes/beneficiaries'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeDeskRouteImport } from './routes/trade-desk'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as FreightRouteImport } from './routes/freight'
import { Route as ImporterRouteImport } from './routes/importer'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as AiGrowthRouteImport } from './routes/ai-growth'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as WhatsappRouteImport } from './routes/whatsapp'

const WalletsRoute = WalletsRouteImport.update({ id: '/wallets', path: '/wallets', getParentRoute: () => rootRouteImport } as any)
const TreasuryRoute = TreasuryRouteImport.update({ id: '/treasury', path: '/treasury', getParentRoute: () => rootRouteImport } as any)
const TransactionsRoute = TransactionsRouteImport.update({ id: '/transactions', path: '/transactions', getParentRoute: () => rootRouteImport } as any)
const TeamRoute = TeamRouteImport.update({ id: '/team', path: '/team', getParentRoute: () => rootRouteImport } as any)
const SettingsRoute = SettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => rootRouteImport } as any)
const OnboardingRoute = OnboardingRouteImport.update({ id: '/onboarding', path: '/onboarding', getParentRoute: () => rootRouteImport } as any)
const FxRoute = FxRouteImport.update({ id: '/fx', path: '/fx', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const BeneficiariesRoute = BeneficiariesRouteImport.update({ id: '/beneficiaries', path: '/beneficiaries', getParentRoute: () => rootRouteImport } as any)
const AiInsightsRoute = AiInsightsRouteImport.update({ id: '/ai-insights', path: '/ai-insights', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const TradeDeskRoute = TradeDeskRouteImport.update({ id: '/trade-desk', path: '/trade-desk', getParentRoute: () => rootRouteImport } as any)
const ShipmentsRoute = ShipmentsRouteImport.update({ id: '/shipments', path: '/shipments', getParentRoute: () => rootRouteImport } as any)
const FreightRoute = FreightRouteImport.update({ id: '/freight', path: '/freight', getParentRoute: () => rootRouteImport } as any)
const ImporterRoute = ImporterRouteImport.update({ id: '/importer', path: '/importer', getParentRoute: () => rootRouteImport } as any)
const SuppliersRoute = SuppliersRouteImport.update({ id: '/suppliers', path: '/suppliers', getParentRoute: () => rootRouteImport } as any)
const CollectionsRoute = CollectionsRouteImport.update({ id: '/collections', path: '/collections', getParentRoute: () => rootRouteImport } as any)
const CardsRoute = CardsRouteImport.update({ id: '/cards', path: '/cards', getParentRoute: () => rootRouteImport } as any)
const AiGrowthRoute = AiGrowthRouteImport.update({ id: '/ai-growth', path: '/ai-growth', getParentRoute: () => rootRouteImport } as any)
const ComplianceRoute = ComplianceRouteImport.update({ id: '/compliance', path: '/compliance', getParentRoute: () => rootRouteImport } as any)
const IntegrationsRoute = IntegrationsRouteImport.update({ id: '/integrations', path: '/integrations', getParentRoute: () => rootRouteImport } as any)
const WhatsappRoute = WhatsappRouteImport.update({ id: '/whatsapp', path: '/whatsapp', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/dashboard': typeof DashboardRoute
  '/fx': typeof FxRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/treasury': typeof TreasuryRoute
  '/wallets': typeof WalletsRoute
  '/trade-desk': typeof TradeDeskRoute
  '/shipments': typeof ShipmentsRoute
  '/freight': typeof FreightRoute
  '/importer': typeof ImporterRoute
  '/suppliers': typeof SuppliersRoute
  '/collections': typeof CollectionsRoute
  '/cards': typeof CardsRoute
  '/ai-growth': typeof AiGrowthRoute
  '/compliance': typeof ComplianceRoute
  '/integrations': typeof IntegrationsRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/dashboard': typeof DashboardRoute
  '/fx': typeof FxRoute
  '/onboarding': typeof OnboardingRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/treasury': typeof TreasuryRoute
  '/wallets': typeof WalletsRoute
  '/trade-desk': typeof TradeDeskRoute
  '/shipments': typeof ShipmentsRoute
  '/freight': typeof FreightRoute
  '/importer': typeof ImporterRoute
  '/suppliers': typeof SuppliersRoute
  '/collections': typeof CollectionsRoute
  '/cards': typeof CardsRoute
  '/ai-growth': typeof AiGrowthRoute
  '/compliance': typeof ComplianceRoute
  '/integrations': typeof IntegrationsRoute
  '/whatsapp': typeof WhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: keyof FileRoutesByFullPath
  fileRoutesByTo: FileRoutesByTo
  to: keyof FileRoutesByTo
  id: keyof FileRoutesById
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  BeneficiariesRoute: typeof BeneficiariesRoute
  DashboardRoute: typeof DashboardRoute
  FxRoute: typeof FxRoute
  OnboardingRoute: typeof OnboardingRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  TransactionsRoute: typeof TransactionsRoute
  TreasuryRoute: typeof TreasuryRoute
  WalletsRoute: typeof WalletsRoute
  TradeDeskRoute: typeof TradeDeskRoute
  ShipmentsRoute: typeof ShipmentsRoute
  FreightRoute: typeof FreightRoute
  ImporterRoute: typeof ImporterRoute
  SuppliersRoute: typeof SuppliersRoute
  CollectionsRoute: typeof CollectionsRoute
  CardsRoute: typeof CardsRoute
  AiGrowthRoute: typeof AiGrowthRoute
  ComplianceRoute: typeof ComplianceRoute
  IntegrationsRoute: typeof IntegrationsRoute
  WhatsappRoute: typeof WhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': { id: '/wallets'; path: '/wallets'; fullPath: '/wallets'; preLoaderRoute: typeof WalletsRouteImport; parentRoute: typeof rootRouteImport }
    '/treasury': { id: '/treasury'; path: '/treasury'; fullPath: '/treasury'; preLoaderRoute: typeof TreasuryRouteImport; parentRoute: typeof rootRouteImport }
    '/transactions': { id: '/transactions'; path: '/transactions'; fullPath: '/transactions'; preLoaderRoute: typeof TransactionsRouteImport; parentRoute: typeof rootRouteImport }
    '/team': { id: '/team'; path: '/team'; fullPath: '/team'; preLoaderRoute: typeof TeamRouteImport; parentRoute: typeof rootRouteImport }
    '/settings': { id: '/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof SettingsRouteImport; parentRoute: typeof rootRouteImport }
    '/onboarding': { id: '/onboarding'; path: '/onboarding'; fullPath: '/onboarding'; preLoaderRoute: typeof OnboardingRouteImport; parentRoute: typeof rootRouteImport }
    '/fx': { id: '/fx'; path: '/fx'; fullPath: '/fx'; preLoaderRoute: typeof FxRouteImport; parentRoute: typeof rootRouteImport }
    '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/beneficiaries': { id: '/beneficiaries'; path: '/beneficiaries'; fullPath: '/beneficiaries'; preLoaderRoute: typeof BeneficiariesRouteImport; parentRoute: typeof rootRouteImport }
    '/ai-insights': { id: '/ai-insights'; path: '/ai-insights'; fullPath: '/ai-insights'; preLoaderRoute: typeof AiInsightsRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/trade-desk': { id: '/trade-desk'; path: '/trade-desk'; fullPath: '/trade-desk'; preLoaderRoute: typeof TradeDeskRouteImport; parentRoute: typeof rootRouteImport }
    '/shipments': { id: '/shipments'; path: '/shipments'; fullPath: '/shipments'; preLoaderRoute: typeof ShipmentsRouteImport; parentRoute: typeof rootRouteImport }
    '/freight': { id: '/freight'; path: '/freight'; fullPath: '/freight'; preLoaderRoute: typeof FreightRouteImport; parentRoute: typeof rootRouteImport }
    '/importer': { id: '/importer'; path: '/importer'; fullPath: '/importer'; preLoaderRoute: typeof ImporterRouteImport; parentRoute: typeof rootRouteImport }
    '/suppliers': { id: '/suppliers'; path: '/suppliers'; fullPath: '/suppliers'; preLoaderRoute: typeof SuppliersRouteImport; parentRoute: typeof rootRouteImport }
    '/collections': { id: '/collections'; path: '/collections'; fullPath: '/collections'; preLoaderRoute: typeof CollectionsRouteImport; parentRoute: typeof rootRouteImport }
    '/cards': { id: '/cards'; path: '/cards'; fullPath: '/cards'; preLoaderRoute: typeof CardsRouteImport; parentRoute: typeof rootRouteImport }
    '/ai-growth': { id: '/ai-growth'; path: '/ai-growth'; fullPath: '/ai-growth'; preLoaderRoute: typeof AiGrowthRouteImport; parentRoute: typeof rootRouteImport }
    '/compliance': { id: '/compliance'; path: '/compliance'; fullPath: '/compliance'; preLoaderRoute: typeof ComplianceRouteImport; parentRoute: typeof rootRouteImport }
    '/integrations': { id: '/integrations'; path: '/integrations'; fullPath: '/integrations'; preLoaderRoute: typeof IntegrationsRouteImport; parentRoute: typeof rootRouteImport }
    '/whatsapp': { id: '/whatsapp'; path: '/whatsapp'; fullPath: '/whatsapp'; preLoaderRoute: typeof WhatsappRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute, AiInsightsRoute, BeneficiariesRoute, DashboardRoute, FxRoute, OnboardingRoute,
  SettingsRoute, TeamRoute, TransactionsRoute, TreasuryRoute, WalletsRoute,
  TradeDeskRoute, ShipmentsRoute, FreightRoute, ImporterRoute, SuppliersRoute,
  CollectionsRoute, CardsRoute, AiGrowthRoute, ComplianceRoute, IntegrationsRoute, WhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
