/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as VerifiedSuppliersRouteImport } from './routes/verified-suppliers'
import { Route as VerifiedBuyersRouteImport } from './routes/verified-buyers'
import { Route as VerificationCenterRouteImport } from './routes/verification-center'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TradeDeskRouteImport } from './routes/trade-desk'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PaymentLinksRouteImport } from './routes/payment-links'
import { Route as PayersRouteImport } from './routes/payers'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MySuppliersRouteImport } from './routes/my-suppliers'
import { Route as LandedCostRouteImport } from './routes/landed-cost'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ImporterRouteImport } from './routes/importer'
import { Route as FxRouteImport } from './routes/fx'
import { Route as FreightInvoicesRouteImport } from './routes/freight-invoices'
import { Route as FreightRouteImport } from './routes/freight'
import { Route as EscrowRouteImport } from './routes/escrow'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as BeneficiariesRouteImport } from './routes/beneficiaries'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as AiGrowthRouteImport } from './routes/ai-growth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeDeskIndexRouteImport } from './routes/trade-desk.index'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as TradeDeskFileIdRouteImport } from './routes/trade-desk.$fileId'
import { Route as TrackIdRouteImport } from './routes/track.$id'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedSuppliersRoute = VerifiedSuppliersRouteImport.update({
  id: '/verified-suppliers',
  path: '/verified-suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifiedBuyersRoute = VerifiedBuyersRouteImport.update({
  id: '/verified-buyers',
  path: '/verified-buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationCenterRoute = VerificationCenterRouteImport.update({
  id: '/verification-center',
  path: '/verification-center',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeDeskRoute = TradeDeskRouteImport.update({
  id: '/trade-desk',
  path: '/trade-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentLinksRoute = PaymentLinksRouteImport.update({
  id: '/payment-links',
  path: '/payment-links',
  getParentRoute: () => rootRouteImport,
} as any)
const PayersRoute = PayersRouteImport.update({
  id: '/payers',
  path: '/payers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MySuppliersRoute = MySuppliersRouteImport.update({
  id: '/my-suppliers',
  path: '/my-suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const LandedCostRoute = LandedCostRouteImport.update({
  id: '/landed-cost',
  path: '/landed-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImporterRoute = ImporterRouteImport.update({
  id: '/importer',
  path: '/importer',
  getParentRoute: () => rootRouteImport,
} as any)
const FxRoute = FxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightInvoicesRoute = FreightInvoicesRouteImport.update({
  id: '/freight-invoices',
  path: '/freight-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightRoute = FreightRouteImport.update({
  id: '/freight',
  path: '/freight',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowRoute = EscrowRouteImport.update({
  id: '/escrow',
  path: '/escrow',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesRoute = BeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AiGrowthRoute = AiGrowthRouteImport.update({
  id: '/ai-growth',
  path: '/ai-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeDeskIndexRoute = TradeDeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TradeDeskRoute,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeDeskFileIdRoute = TradeDeskFileIdRouteImport.update({
  id: '/$fileId',
  path: '/$fileId',
  getParentRoute: () => TradeDeskRoute,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-growth': typeof AiGrowthRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/buyers': typeof BuyersRoute
  '/cards': typeof CardsRoute
  '/collections': typeof CollectionsRoute
  '/compliance': typeof ComplianceRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/escrow': typeof EscrowRoute
  '/freight': typeof FreightRoute
  '/freight-invoices': typeof FreightInvoicesRoute
  '/fx': typeof FxRoute
  '/importer': typeof ImporterRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/landed-cost': typeof LandedCostRoute
  '/my-suppliers': typeof MySuppliersRoute
  '/onboarding': typeof OnboardingRoute
  '/organization': typeof OrganizationRoute
  '/payers': typeof PayersRoute
  '/payment-links': typeof PaymentLinksRoute
  '/payments': typeof PaymentsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/trade-desk': typeof TradeDeskRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/treasury': typeof TreasuryRoute
  '/verification-center': typeof VerificationCenterRoute
  '/verified-buyers': typeof VerifiedBuyersRoute
  '/verified-suppliers': typeof VerifiedSuppliersRoute
  '/wallets': typeof WalletsRoute
  '/welcome': typeof WelcomeRoute
  '/whatsapp': typeof WhatsappRoute
  '/track/$id': typeof TrackIdRoute
  '/trade-desk/$fileId': typeof TradeDeskFileIdRoute
  '/track/': typeof TrackIndexRoute
  '/trade-desk/': typeof TradeDeskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-growth': typeof AiGrowthRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/buyers': typeof BuyersRoute
  '/cards': typeof CardsRoute
  '/collections': typeof CollectionsRoute
  '/compliance': typeof ComplianceRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/escrow': typeof EscrowRoute
  '/freight': typeof FreightRoute
  '/freight-invoices': typeof FreightInvoicesRoute
  '/fx': typeof FxRoute
  '/importer': typeof ImporterRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/landed-cost': typeof LandedCostRoute
  '/my-suppliers': typeof MySuppliersRoute
  '/onboarding': typeof OnboardingRoute
  '/organization': typeof OrganizationRoute
  '/payers': typeof PayersRoute
  '/payment-links': typeof PaymentLinksRoute
  '/payments': typeof PaymentsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/transactions': typeof TransactionsRoute
  '/treasury': typeof TreasuryRoute
  '/verification-center': typeof VerificationCenterRoute
  '/verified-buyers': typeof VerifiedBuyersRoute
  '/verified-suppliers': typeof VerifiedSuppliersRoute
  '/wallets': typeof WalletsRoute
  '/welcome': typeof WelcomeRoute
  '/whatsapp': typeof WhatsappRoute
  '/track/$id': typeof TrackIdRoute
  '/trade-desk/$fileId': typeof TradeDeskFileIdRoute
  '/track': typeof TrackIndexRoute
  '/trade-desk': typeof TradeDeskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-growth': typeof AiGrowthRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/beneficiaries': typeof BeneficiariesRoute
  '/buyers': typeof BuyersRoute
  '/cards': typeof CardsRoute
  '/collections': typeof CollectionsRoute
  '/compliance': typeof ComplianceRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/escrow': typeof EscrowRoute
  '/freight': typeof FreightRoute
  '/freight-invoices': typeof FreightInvoicesRoute
  '/fx': typeof FxRoute
  '/importer': typeof ImporterRoute
  '/integrations': typeof IntegrationsRoute
  '/invoices': typeof InvoicesRoute
  '/landed-cost': typeof LandedCostRoute
  '/my-suppliers': typeof MySuppliersRoute
  '/onboarding': typeof OnboardingRoute
  '/organization': typeof OrganizationRoute
  '/payers': typeof PayersRoute
  '/payment-links': typeof PaymentLinksRoute
  '/payments': typeof PaymentsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/shipments': typeof ShipmentsRoute
  '/suppliers': typeof SuppliersRoute
  '/team': typeof TeamRoute
  '/trade-desk': typeof TradeDeskRouteWithChildren
  '/transactions': typeof TransactionsRoute
  '/treasury': typeof TreasuryRoute
  '/verification-center': typeof VerificationCenterRoute
  '/verified-buyers': typeof VerifiedBuyersRoute
  '/verified-suppliers': typeof VerifiedSuppliersRoute
  '/wallets': typeof WalletsRoute
  '/welcome': typeof WelcomeRoute
  '/whatsapp': typeof WhatsappRoute
  '/track/$id': typeof TrackIdRoute
  '/trade-desk/$fileId': typeof TradeDeskFileIdRoute
  '/track/': typeof TrackIndexRoute
  '/trade-desk/': typeof TradeDeskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-growth'
    | '/ai-insights'
    | '/approvals'
    | '/beneficiaries'
    | '/buyers'
    | '/cards'
    | '/collections'
    | '/compliance'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/escrow'
    | '/freight'
    | '/freight-invoices'
    | '/fx'
    | '/importer'
    | '/integrations'
    | '/invoices'
    | '/landed-cost'
    | '/my-suppliers'
    | '/onboarding'
    | '/organization'
    | '/payers'
    | '/payment-links'
    | '/payments'
    | '/reconciliation'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/suppliers'
    | '/team'
    | '/trade-desk'
    | '/transactions'
    | '/treasury'
    | '/verification-center'
    | '/verified-buyers'
    | '/verified-suppliers'
    | '/wallets'
    | '/welcome'
    | '/whatsapp'
    | '/track/$id'
    | '/trade-desk/$fileId'
    | '/track/'
    | '/trade-desk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-growth'
    | '/ai-insights'
    | '/approvals'
    | '/beneficiaries'
    | '/buyers'
    | '/cards'
    | '/collections'
    | '/compliance'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/escrow'
    | '/freight'
    | '/freight-invoices'
    | '/fx'
    | '/importer'
    | '/integrations'
    | '/invoices'
    | '/landed-cost'
    | '/my-suppliers'
    | '/onboarding'
    | '/organization'
    | '/payers'
    | '/payment-links'
    | '/payments'
    | '/reconciliation'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/suppliers'
    | '/team'
    | '/transactions'
    | '/treasury'
    | '/verification-center'
    | '/verified-buyers'
    | '/verified-suppliers'
    | '/wallets'
    | '/welcome'
    | '/whatsapp'
    | '/track/$id'
    | '/trade-desk/$fileId'
    | '/track'
    | '/trade-desk'
  id:
    | '__root__'
    | '/'
    | '/ai-growth'
    | '/ai-insights'
    | '/approvals'
    | '/beneficiaries'
    | '/buyers'
    | '/cards'
    | '/collections'
    | '/compliance'
    | '/customers'
    | '/dashboard'
    | '/documents'
    | '/escrow'
    | '/freight'
    | '/freight-invoices'
    | '/fx'
    | '/importer'
    | '/integrations'
    | '/invoices'
    | '/landed-cost'
    | '/my-suppliers'
    | '/onboarding'
    | '/organization'
    | '/payers'
    | '/payment-links'
    | '/payments'
    | '/reconciliation'
    | '/reports'
    | '/settings'
    | '/shipments'
    | '/suppliers'
    | '/team'
    | '/trade-desk'
    | '/transactions'
    | '/treasury'
    | '/verification-center'
    | '/verified-buyers'
    | '/verified-suppliers'
    | '/wallets'
    | '/welcome'
    | '/whatsapp'
    | '/track/$id'
    | '/trade-desk/$fileId'
    | '/track/'
    | '/trade-desk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiGrowthRoute: typeof AiGrowthRoute
  AiInsightsRoute: typeof AiInsightsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BeneficiariesRoute: typeof BeneficiariesRoute
  BuyersRoute: typeof BuyersRoute
  CardsRoute: typeof CardsRoute
  CollectionsRoute: typeof CollectionsRoute
  ComplianceRoute: typeof ComplianceRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  EscrowRoute: typeof EscrowRoute
  FreightRoute: typeof FreightRoute
  FreightInvoicesRoute: typeof FreightInvoicesRoute
  FxRoute: typeof FxRoute
  ImporterRoute: typeof ImporterRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InvoicesRoute: typeof InvoicesRoute
  LandedCostRoute: typeof LandedCostRoute
  MySuppliersRoute: typeof MySuppliersRoute
  OnboardingRoute: typeof OnboardingRoute
  OrganizationRoute: typeof OrganizationRoute
  PayersRoute: typeof PayersRoute
  PaymentLinksRoute: typeof PaymentLinksRoute
  PaymentsRoute: typeof PaymentsRoute
  ReconciliationRoute: typeof ReconciliationRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ShipmentsRoute: typeof ShipmentsRoute
  SuppliersRoute: typeof SuppliersRoute
  TeamRoute: typeof TeamRoute
  TradeDeskRoute: typeof TradeDeskRouteWithChildren
  TransactionsRoute: typeof TransactionsRoute
  TreasuryRoute: typeof TreasuryRoute
  VerificationCenterRoute: typeof VerificationCenterRoute
  VerifiedBuyersRoute: typeof VerifiedBuyersRoute
  VerifiedSuppliersRoute: typeof VerifiedSuppliersRoute
  WalletsRoute: typeof WalletsRoute
  WelcomeRoute: typeof WelcomeRoute
  WhatsappRoute: typeof WhatsappRoute
  TrackIdRoute: typeof TrackIdRoute
  TrackIndexRoute: typeof TrackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified-suppliers': {
      id: '/verified-suppliers'
      path: '/verified-suppliers'
      fullPath: '/verified-suppliers'
      preLoaderRoute: typeof VerifiedSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verified-buyers': {
      id: '/verified-buyers'
      path: '/verified-buyers'
      fullPath: '/verified-buyers'
      preLoaderRoute: typeof VerifiedBuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-center': {
      id: '/verification-center'
      path: '/verification-center'
      fullPath: '/verification-center'
      preLoaderRoute: typeof VerificationCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-desk': {
      id: '/trade-desk'
      path: '/trade-desk'
      fullPath: '/trade-desk'
      preLoaderRoute: typeof TradeDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-links': {
      id: '/payment-links'
      path: '/payment-links'
      fullPath: '/payment-links'
      preLoaderRoute: typeof PaymentLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payers': {
      id: '/payers'
      path: '/payers'
      fullPath: '/payers'
      preLoaderRoute: typeof PayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-suppliers': {
      id: '/my-suppliers'
      path: '/my-suppliers'
      fullPath: '/my-suppliers'
      preLoaderRoute: typeof MySuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landed-cost': {
      id: '/landed-cost'
      path: '/landed-cost'
      fullPath: '/landed-cost'
      preLoaderRoute: typeof LandedCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importer': {
      id: '/importer'
      path: '/importer'
      fullPath: '/importer'
      preLoaderRoute: typeof ImporterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx': {
      id: '/fx'
      path: '/fx'
      fullPath: '/fx'
      preLoaderRoute: typeof FxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight-invoices': {
      id: '/freight-invoices'
      path: '/freight-invoices'
      fullPath: '/freight-invoices'
      preLoaderRoute: typeof FreightInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight': {
      id: '/freight'
      path: '/freight'
      fullPath: '/freight'
      preLoaderRoute: typeof FreightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow': {
      id: '/escrow'
      path: '/escrow'
      fullPath: '/escrow'
      preLoaderRoute: typeof EscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries': {
      id: '/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/beneficiaries'
      preLoaderRoute: typeof BeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-growth': {
      id: '/ai-growth'
      path: '/ai-growth'
      fullPath: '/ai-growth'
      preLoaderRoute: typeof AiGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-desk/': {
      id: '/trade-desk/'
      path: '/'
      fullPath: '/trade-desk/'
      preLoaderRoute: typeof TradeDeskIndexRouteImport
      parentRoute: typeof TradeDeskRoute
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-desk/$fileId': {
      id: '/trade-desk/$fileId'
      path: '/$fileId'
      fullPath: '/trade-desk/$fileId'
      preLoaderRoute: typeof TradeDeskFileIdRouteImport
      parentRoute: typeof TradeDeskRoute
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TradeDeskRouteChildren {
  TradeDeskFileIdRoute: typeof TradeDeskFileIdRoute
  TradeDeskIndexRoute: typeof TradeDeskIndexRoute
}

const TradeDeskRouteChildren: TradeDeskRouteChildren = {
  TradeDeskFileIdRoute: TradeDeskFileIdRoute,
  TradeDeskIndexRoute: TradeDeskIndexRoute,
}

const TradeDeskRouteWithChildren = TradeDeskRoute._addFileChildren(
  TradeDeskRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiGrowthRoute: AiGrowthRoute,
  AiInsightsRoute: AiInsightsRoute,
  ApprovalsRoute: ApprovalsRoute,
  BeneficiariesRoute: BeneficiariesRoute,
  BuyersRoute: BuyersRoute,
  CardsRoute: CardsRoute,
  CollectionsRoute: CollectionsRoute,
  ComplianceRoute: ComplianceRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  EscrowRoute: EscrowRoute,
  FreightRoute: FreightRoute,
  FreightInvoicesRoute: FreightInvoicesRoute,
  FxRoute: FxRoute,
  ImporterRoute: ImporterRoute,
  IntegrationsRoute: IntegrationsRoute,
  InvoicesRoute: InvoicesRoute,
  LandedCostRoute: LandedCostRoute,
  MySuppliersRoute: MySuppliersRoute,
  OnboardingRoute: OnboardingRoute,
  OrganizationRoute: OrganizationRoute,
  PayersRoute: PayersRoute,
  PaymentLinksRoute: PaymentLinksRoute,
  PaymentsRoute: PaymentsRoute,
  ReconciliationRoute: ReconciliationRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ShipmentsRoute: ShipmentsRoute,
  SuppliersRoute: SuppliersRoute,
  TeamRoute: TeamRoute,
  TradeDeskRoute: TradeDeskRouteWithChildren,
  TransactionsRoute: TransactionsRoute,
  TreasuryRoute: TreasuryRoute,
  VerificationCenterRoute: VerificationCenterRoute,
  VerifiedBuyersRoute: VerifiedBuyersRoute,
  VerifiedSuppliersRoute: VerifiedSuppliersRoute,
  WalletsRoute: WalletsRoute,
  WelcomeRoute: WelcomeRoute,
  WhatsappRoute: WhatsappRoute,
  TrackIdRoute: TrackIdRoute,
  TrackIndexRoute: TrackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
